### ISSUE TITLE
Role & Group Definition

### ISSUE THREAD

**Issue by Yousuf24100286** [Yousuf24100286/findyourtutor#4]
### Description
In user authentication we are using two different variables to differentiate users
- `role` - to define the role of the user which is either `admin`, `student` or `tutor`
- `group` - is to define which category of the provided role does the user belongs to

### Concerns

Raised for @adeel838 to answer
- what values of group variable should be used for `student` role ? `parent` and `student`
- what values of group variable should be used for `tutor` role ? `alumni` and `student`
- if above is the case how to differentiate between the `tutor => student` and `student => student` group
- what values should be used for admin, since we are not using any differentiation within admin users

Raised for @hammadtariq838 to answer
- should we be hardcoding these values into schema or making these dynamic into database for catering future changes

**Comment by Yousuf24100286** [comment]
`role` definition has been hardcoded into the schema in #3

Waiting for clarification on `group`

**Comment by adeel838** [comment]
For student role, clarification is needed from business end. If law requires to identify between under 18 students, we can automatically link underage students with parents' account. 

Values of group variable for student are parent and student.
Values of group variable for tutor are enrolled and alumni.
Values of group variable for Admin is empty string.
